### ISSUE TITLE
Logo proposal for steemacces

### ISSUE THREAD

**Issue by radudangratian** [caspernikus/steemaccess#1]
Hello! I saw that you don't have a logo for this awesome project.I made a logo for you.Here it's my proposal.
![1](https://user-images.githubusercontent.com/34451833/38052452-fc7a930e-32d9-11e8-8ab0-8f36dac871aa.png)

I hope you will like it!

**Comment by caspernikus** [comment]
Hi @radudangratin
Thanks for your logo and different variations of it as have requested.

They look awesome and are now integrated into the Website / GitHub Repository!
